name: mushroom_mart
description: A simple Flutter + Firebase starter
publish_to: "none"
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.1.0

flutter:
  uses-material-design: true
