name: mushroom_mart
description: A new Flutter project.
publish_to: 'none' # अगर तुम pub.dev पर publish नहीं करना चाहते

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core
  firebase_core: ^4.1.0

  # Firebase Authentication
  firebase_auth: ^6.0.2

  # Cloud Firestore
  cloud_firestore: ^6.0.1

  # Firebase Storage
  firebase_storage: ^13.0.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
